name: CI

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 10

      - name: Run tests
        env:
          DATABASE_URL: postgres://izanami:password@127.0.0.1:5432/izanami_backend_development
          RAILS_ENV: development
        run: |
          ./bin/rails db:migrate
          bundle exec rspec
